# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20171115_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='hero_kicker',
            field=models.CharField(blank=True, help_text='If this is left blank it will use the page title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='hero_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
