# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0006_auto_20151002_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_title', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=140)),
                ('link_url', models.CharField(blank=True, help_text='If you want to link to an external page, please use this.', max_length=200, null=True)),
                ('link_page', models.ForeignKey(blank=True, help_text='If you want to link to an internal page, please use this.', null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
            ],
        ),
    ]
