# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltoaction',
            name='link_text',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
