# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0002_auto_20171113_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='address',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='address_link_page',
            new_name='contact_link_page',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='address_link_text',
            new_name='contact_link_text',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='address_link_url',
            new_name='contact_link_url',
        ),
        migrations.RenameField(
            model_name='footer',
            old_name='address_title',
            new_name='contact_title',
        ),
    ]
