# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0003_auto_20171113_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='contact',
            new_name='contact_address',
        ),
    ]
