# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0005_auto_20171113_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='privacy_policy_link',
            new_name='privacy_policy_url',
        ),
    ]
