# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0006_auto_20171113_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='about_text',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='contact_address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
