# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0007_auto_20171113_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerlink',
            old_name='link_text',
            new_name='text',
        ),
    ]
