# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 14:16
from __future__ import unicode_literals

import cms.apps.media.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20170407_1442'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsection',
            name='background_colour',
            field=models.CharField(choices=[('white', 'White')], default='white', max_length=255),
        ),
        migrations.AddField(
            model_name='contentsection',
            name='image_side',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='contentsection',
            name='mobile_image',
            field=cms.apps.media.models.ImageRefField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.File'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='type',
            field=models.CharField(choices=[('Heroes', [('landing-hero', 'Landing hero')]), ('Images', [('full-width', 'Full width'), ('split', 'Split')]), ('Text', [('centered', 'Centered'), ('dual-column', 'Dual column')])], max_length=100),
        ),
    ]
