# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_auto_20171115_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsection',
            name='kicker',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='type',
            field=models.CharField(choices=[('Heroes', [('heroes-landing-hero', 'Landing hero')]), ('Images', [('images-full-width', 'Full width'), ('images-split', 'Split')]), ('Text', [('text-centered', 'Centered'), ('text-dual-column', 'Dual column')])], max_length=100),
        ),
    ]
